import React, { useState } from 'react';
import DatePicker from 'react-datepicker';
import { useNavigate } from 'react-router-dom';
import 'react-datepicker/dist/react-datepicker.css';

export default function JobsCreate() {
  const navigate = useNavigate();

  // Core form state
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [requirementId, setRequirementId] = useState('');
  const [title, setTitle] = useState('');
  const [openingDate, setOpeningDate] = useState(new Date());
  const [closingDate, setClosingDate] = useState(null);
  const [location, setLocation] = useState('');
  const [workmode, setWorkMode] = useState('');
  const [slots, setSlots] = useState(1);
  const [status, setStatus] = useState('open');
  const [jd, setJD] = useState('');

  // ------------------------------------------------------------------
  // Weightage (Skills, Experience, Education) using two boundaries
  // A = split1 (end of Skills)
  // B = split2 (end of Experience)
  // Skills     = A
  // Experience = B - A
  // Education  = 100 - B
  // ------------------------------------------------------------------
  const TOTAL = 100;
  const STEP = 1;        // whole percentage points (use 0.5 if needed)
  const MIN_SEGMENT = 5; // minimum % per section (set to 0 if you want no min)

  const [split1, setSplit1] = useState(60); // Skills boundary
  const [split2, setSplit2] = useState(80); // Experience boundary

  const skillW = split1;
  const expW = split2 - split1;
  const eduW = TOTAL - split2;

  const handleSplit1Change = (e) => {
    const val = Number(e.target.value);
    // split1 must be <= split2 - MIN_SEGMENT
    setSplit1(Math.max(0, Math.min(val, split2 - MIN_SEGMENT)));
  };

  const handleSplit2Change = (e) => {
    const val = Number(e.target.value);
    // split2 must be >= split1 + MIN_SEGMENT
    setSplit2(Math.min(TOTAL, Math.max(val, split1 + MIN_SEGMENT)));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsSubmitting(true);

    const payload = {
      // requirement_id: requirementId,
      title: title,
      location: location,
      workmode: workmode,
      opening_date: openingDate?.toISOString().split('T')[0],
      closing_date: closingDate ? closingDate.toISOString().split('T')[0] : null,
      slots: Number(slots),
      status: status,
      jd: jd,
      // New: send the derived weightage
      weightage: {
        skills: skillW,      // integer 0..100
        experience: expW,    // integer 0..100
        education: eduW,     // integer 0..100
      },
    };

    try {
      const response = await fetch('http://localhost:8000/v1/jobs/create', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.detail || 'Failed to create job.');
      }

      alert('Job created successfully!', response.requirement_id);
      navigate('/v1/jobs');
    } catch (err) {
      alert(`Error: ${err.message}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 overflow-auto">
      {/* Header / Hero (Insights-style gradient) */}
      <div className="bg-gradient-to-r from-indigo-600/20 via-purple-600/20 to-fuchsia-600/20 border-b border-slate-800">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
          <div className="flex flex-col gap-1">
            <h1 className="text-2xl font-bold tracking-tight text-slate-100">
              Virtual TA <span className="text-indigo-400">Create Job</span>
            </h1>
            <p className="text-sm text-slate-400">
              Fill in all required fields to create a new job opening.
            </p>
          </div>
        </div>
      </div>

      {/* Body */}
      <div className="mx-auto max-w-3xl px-4 py-8">
        <div className="mx-auto w-full rounded-xl border border-slate-800 bg-slate-900/50 p-6 shadow-sm backdrop-blur">
          <h2 className="text-xl font-semibold tracking-tight text-slate-100">
            Create Job
          </h2>
          <p className="mt-1 text-sm text-slate-400">
            Provide core details like requirement ID, dates, and JD.
          </p>

          <form className="mt-6 space-y-5" onSubmit={handleSubmit} noValidate>
            {/* Requirement ID */}
            <div>
              <label className="block text-sm font-medium text-slate-300">
                Requirement ID <span className="text-rose-400">*</span>
              </label>
              <p className="text-slate-400 text-xs mt-1">
                This will be auto-generated by the system (e.g., REQ-2025-0101).
              </p>
            </div>

            {/* Title */}
            <div>
              <label htmlFor="title" className="block text-sm font-medium text-slate-300">
                Title <span className="text-rose-400">*</span>
              </label>
              <input
                id="title"
                name="title"
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="e.g., Teaching Assistant - Algorithms"
                className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900/60 px-3 py-2 text-slate-100 placeholder:text-slate-500 focus:outline-none focus:ring-2 focus:ring-indigo-400"
              />
            </div>

            {/* Dates */}
            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <label className="block text-sm font-medium text-slate-300">
                  Opening Date <span className="text-rose-400">*</span>
                </label>
                <DatePicker
                  selected={openingDate}
                  onChange={(date) => setOpeningDate(date)}
                  className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900/60 px-3 py-2 text-slate-100 placeholder:text-slate-500 focus:outline-none focus:ring-2 focus:ring-indigo-400"
                  dateFormat="yyyy-MM-dd"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-300">
                  Closing Date <span className="text-rose-400">*</span>
                </label>
                <DatePicker
                  selected={closingDate}
                  onChange={(date) => setClosingDate(date)}
                  placeholderText="e.g. 2025-11-05"
                  className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900/60 px-3 py-2 text-slate-100 placeholder:text-slate-500 focus:outline-none focus:ring-2 focus:ring-indigo-400"
                  dateFormat="yyyy-MM-dd"
                  minDate={openingDate}
                />
              </div>
            </div>

            {/* Location & Work Mode */}
            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <label htmlFor="location" className="block text-sm font-medium text-slate-300">
                  Location <span className="text-rose-400">*</span>
                </label>
                <input
                  id="location"
                  name="location"
                  type="text"
                  value={location}
                  onChange={(e) => setLocation(e.target.value)}
                  placeholder="e.g., Pune, India"
                  className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900/60 px-3 py-2 text-slate-100 placeholder:text-slate-500 focus:outline-none focus:ring-2 focus:ring-indigo-400"
                />
              </div>

              <div>
                <label htmlFor="workmode" className="block text-sm font-medium text-slate-300">
                  Working Mode <span className="text-rose-400">*</span>
                </label>
                <input
                  id="workmode"
                  name="workmode"
                  type="text"
                  value={workmode}
                  onChange={(e) => setWorkMode(e.target.value)}
                  placeholder="e.g., Full-Time/Part-Time or Remote/Hybrid"
                  className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900/60 px-3 py-2 text-slate-100 placeholder:text-slate-500 focus:outline-none focus:ring-2 focus:ring-indigo-400"
                />
              </div>
            </div>

            {/* Slots & Status */}
            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <label htmlFor="slots" className="block text-sm font-medium text-slate-300">
                  Slots <span className="text-rose-400">*</span>
                </label>
                <input
                  id="slots"
                  name="slots"
                  type="number"
                  min={1}
                  value={slots}
                  onChange={(e) => setSlots(Number(e.target.value))}
                  className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900/60 px-3 py-2 text-slate-100 placeholder:text-slate-500 focus:outline-none focus:ring-2 focus:ring-indigo-400"
                />
              </div>

              <div>
                <label htmlFor="status" className="block text-sm font-medium text-slate-300">
                  Status <span className="text-rose-400">*</span>
                </label>
                <select
                  id="status"
                  name="status"
                  value={status}
                  onChange={(e) => setStatus(e.target.value)}
                  className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900/60 px-3 py-2 text-slate-100 focus:outline-none focus:ring-2 focus:ring-indigo-400"
                >
                  <option value="open">Open</option>
                  {/* <option value="closed">Closed</option> */}
                </select>
              </div>
            </div>

            {/* Job Description */}
            <div>
              <label htmlFor="jd" className="block text-sm font-medium text-slate-300">
                Job Description <span className="text-rose-400">*</span>
              </label>
              <textarea
                id="jd"
                name="jd"
                value={jd}
                onChange={(e) => setJD(e.target.value)}
                placeholder="Responsibilities, essentials, preferred."
                rows={6}
                className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900/60 px-3 py-2 text-slate-100 placeholder:text-slate-500 focus:outline-none focus:ring-2 focus:ring-indigo-400"
              />
            </div>

            {/* --- NEW: Weightage (Skills, Experience, Education) --- */}
            <div>
              <div className="flex flex-wrap items-end justify-between gap-2">
                <label className="block text-sm font-medium text-slate-300">
                  Weightage (must total 100)
                </label>

                {/* Live values */}
                <div className="flex items-center gap-2 text-xs">
                  <span className="inline-flex items-center gap-1 rounded-full bg-slate-800/70 px-2 py-1 text-indigo-300">
                    <span className="h-2 w-2 rounded-full bg-indigo-500" /> Skills: {skillW}%
                  </span>
                  <span className="inline-flex items-center gap-1 rounded-full bg-slate-800/70 px-2 py-1 text-violet-300">
                    <span className="h-2 w-2 rounded-full bg-violet-500" /> Experience: {expW}%
                  </span>
                  <span className="inline-flex items-center gap-1 rounded-full bg-slate-800/70 px-2 py-1 text-fuchsia-300">
                    <span className="h-2 w-2 rounded-full bg-fuchsia-500" /> Education: {eduW}%
                  </span>
                </div>
              </div>

              <div className="mt-3">
                {/* Slider wrapper */}
                <div className="relative h-10 select-none">
                  {/* Track background */}
                  <div className="absolute top-1/2 h-1 w-full -translate-y-1/2 rounded-full bg-slate-700" />

                  {/* Segments (stacked to form the full bar) */}
                  {/* Skills segment [0..split1] */}
                  <div
                    className="absolute top-1/2 h-1 -translate-y-1/2 rounded-l-full bg-indigo-500/80"
                    style={{ left: '0%', width: `${split1}%` }}
                  />
                  {/* Experience segment [split1..split2] */}
                  <div
                    className="absolute top-1/2 h-1 -translate-y-1/2 bg-violet-500/80"
                    style={{ left: `${split1}%`, width: `${split2 - split1}%` }}
                  />
                  {/* Education segment [split2..100] */}
                  <div
                    className="absolute top-1/2 h-1 -translate-y-1/2 rounded-r-full bg-fuchsia-500/80"
                    style={{ left: `${split2}%`, width: `${100 - split2}%` }}
                  />

                  {/* Thumb A (boundary Skills|Experience) */}
                  <input
                    type="range"
                    min={0}
                    max={TOTAL}
                    step={STEP}
                    value={split1}
                    onChange={handleSplit1Change}
                    className="pointer-events-auto absolute left-0 top-0 h-10 w-full appearance-none bg-transparent"
                    aria-label="Adjust boundary between Skills and Experience"
                  />
                  {/* Thumb B (boundary Experience|Education) */}
                  <input
                    type="range"
                    min={0}
                    max={TOTAL}
                    step={STEP}
                    value={split2}
                    onChange={handleSplit2Change}
                    className="pointer-events-auto absolute left-0 top-0 h-10 w-full appearance-none bg-transparent"
                    aria-label="Adjust boundary between Experience and Education"
                  />

                  {/* Thumb styles */}
                  <style>{`
                    input[type="range"] {
                      -webkit-appearance: none;
                    }
                    input[type="range"]::-webkit-slider-thumb {
                      -webkit-appearance: none;
                      appearance: none;
                      height: 18px;
                      width: 18px;
                      border-radius: 9999px;
                      background: #818cf8; /* indigo-400/500-ish */
                      border: 2px solid #0f172a; /* slate-900 */
                      box-shadow: 0 0 0 4px rgba(129, 140, 248, 0.25);
                      cursor: pointer;
                      position: relative;
                      z-index: 10;
                    }
                    input[type="range"]::-moz-range-thumb {
                      height: 18px;
                      width: 18px;
                      border-radius: 9999px;
                      background: #818cf8;
                      border: 2px solid #0f172a;
                      box-shadow: 0 0 0 4px rgba(129, 140, 248, 0.25);
                      cursor: pointer;
                      position: relative;
                      z-index: 10;
                    }
                    /* hide native track */
                    input[type="range"]::-webkit-slider-runnable-track {
                      height: 1px;
                      background: transparent;
                    }
                    input[type="range"]::-moz-range-track {
                      height: 1px;
                      background: transparent.
                    }
                  `}</style>
                </div>

                {/* Labels under the track */}
                <div className="mt-2 flex justify-between text-[11px] text-slate-500">
                  <span>0%</span>
                  <span>100%</span>
                </div>
              </div>
            </div>

            {/* Actions */}
            {/* Actions */}
<div className="flex items-center gap-3 pt-2">
  <button
    type="submit"
    disabled={isSubmitting}
    className={`inline-flex items-center justify-center rounded-md px-4 py-2 text-sm font-semibold text-white shadow focus:outline-none focus:ring-2 focus:ring-indigo-400
      ${isSubmitting
        ? 'cursor-not-allowed bg-indigo-500/60'
        : 'bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700'}`}
  >
    {isSubmitting ? (
      <span className="inline-flex items-center gap-2">
        <span className="h-4 w-4 animate-spin rounded-full border-2 border-white/40 border-t-white" />
        Creating...
      </span>
    ) : (
      'Create Job'
    )}
  </button>

  <button
    type="button"
    disabled={isSubmitting}
    onClick={() => navigate('/v1/jobs')}
    className={`inline-flex items-center justify-center rounded-md border border-slate-700 px-4 py-2 text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-indigo-400
      ${isSubmitting ? 'cursor-not-allowed bg-slate-900/40 text-slate-400' : 'bg-slate-900/60 text-slate-200 hover:bg-slate-800'}`}
  >
    Cancel
  </button>
</div>
          </form>
        </div>

        <div className="h-10" />
      </div>
    </div>
  );
}